name: C++ Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  docker-test:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Checkout repository
      uses: actions/checkout@v4

    - name: 🐳 Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: .github/workflows/Dockerfile
        tags: cpp-dev-env:latest
        load: true  

    - name: 🔧 Compile and Run Tests
      run: |
        docker run --rm -v ${{ github.workspace }}:/app -w /app cpp-dev-env:latest bash -c "
          g++ -std=c++17 -fsanitize=address -fno-omit-frame-pointer -g -O0 -Wall -Wextra -I. -Isrc main.cpp tests/*.cpp build/DoublyLinkedList.o -o main &&
          ./main
        "

  notify-discord:
    needs: [docker-test]
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: 📤 Send Discord notification
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.WEB_HOOK_THREAD }}
        run: |
          AUTHOR_NAME="${{ github.actor }}"
          EVENT_NAME="${{ github.event_name }}"
          REPO_NAME="${{ github.repository }}"
          COMMIT_MSG="${{ github.event.head_commit.message }}"
          
          if [ "$EVENT_NAME" == "pull_request" ]; then
            HEAD_BRANCH="${{ github.event.pull_request.head.ref }}"
            BASE_BRANCH="${{ github.event.pull_request.base.ref }}"
            BRANCH_INFO="\`${HEAD_BRANCH}\` → \`${BASE_BRANCH}\`"
          else
            CURRENT_BRANCH="${GITHUB_REF##*/}"
            BRANCH_INFO="\`${CURRENT_BRANCH}\`"
          fi

          # Gửi message tới Discord
          curl -H "Content-Type: application/json" \
            -X POST \
            -d @- "$DISCORD_WEBHOOK_URL" <<EOF
          {
            "content": "✅ \`${{ github.workflow }}\` passed!\n**Author:** ${AUTHOR_NAME}\n**Branch:** ${BRANCH_INFO}\n**Event:** \`${EVENT_NAME}\`\n**Commit:** ${COMMIT_MSG}\n👉 [View Run](${{ github.server_url }}/${REPO_NAME}/actions/runs/${{ github.run_id }})"
          }
